name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'microsoft'

      - name: Extract project version
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        id: get_version
        run: |
          VERSION=$(./gradlew properties -q | grep -w "^version" | head -n 1 | sed 's/version[[:space:]]*[:=][[:space:]]*//' | tr -d '[:space:]')
          
          if [ -z "$VERSION" ]; then
            echo "::error::Could not extract version from Gradle."
            exit 1
          fi
          
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"

      - name: Check if release exists
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        id: check_release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if gh release view "v${{ env.VERSION }}" >/dev/null 2>&1; then
            echo "EXISTS=true" >> $GITHUB_OUTPUT
            echo "::error::Release v${{ env.VERSION }} already exists! You probably forgot to update the version in your build.gradle."
            exit 1
          else
            echo "EXISTS=false" >> $GITHUB_OUTPUT
          fi

      - name: Validate README.md version badges
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "Checking against version: ${{ env.VERSION }}"
          EXPECTED_VERSION="${{ env.VERSION }}"
          
          if [ -z "$EXPECTED_VERSION" ]; then
            echo "::error::Version could not be extracted from Gradle."
            exit 1
          fi

          FAILED_FILES=()

          while IFS= read -r file; do
            CURRENT_VERSION=$(grep -oE "Version-[0-9]+\.[0-9]+(\.[0-9]+)?" "$file" | sed 's/Version-//')
            
            if [ "$CURRENT_VERSION" != "$EXPECTED_VERSION" ]; then
              echo "::error file=$file::Version mismatch. Found $CURRENT_VERSION, expected $EXPECTED_VERSION"
              FAILED_FILES+=("$file")
            fi
          done < <(find . -name "README.md")

          if [ ${#FAILED_FILES[@]} -ne 0 ]; then
            echo "::error::The following README.md files have incorrect version badges:"
            for f in "${FAILED_FILES[@]}"; do
              echo "   -> $f"
            done
            exit 1
          fi

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_25_X64 }}
        run: ./gradlew build

      - name: capture build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: build/libs/

      - name: Create GitHub Release
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && steps.check_release.outputs.EXISTS == 'false'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: v${{ env.VERSION }}
          body_path: README.md
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}